### PR TITLE
Fix gradle build

### PR DESCRIPTION
**Pull request by rdegnan**
I noticed that the tests were not being run as part of the build, and when they were run they were failing due to dependency mismatches. This pull request updates reactorIpcVersion and reactorCoreVersion and cleans up some other gradle issues that were preventing the tests from running.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@rdegnan Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-aeron&pullRequestId=7)!

[Click here](https://cla.pivotal.io/sync/reactor?repositoryId=reactor/reactor-aeron&pullRequestId=7) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@rdegnan Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-aeron&pullRequestId=7)!

**Comment by kadyana** [comment]
Thank you for the PR. Looking into it.

**Comment by kadyana** [comment]
Could we have a chat to discuss your interest in the module?

**Pull request merged**
